from typing import NoReturn

class PyroFile:
    """File-like object for accessing local and cloud storage."""

    def __init__(self, path: str, mode: str = "r") -> None: ...

    def read(self, size: int | None = None) -> bytes: ...
    def write(self, data: bytes) -> int: ...
    def seek(self, offset: int, whence: int = 0) -> int: ...
    def tell(self) -> int: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...

    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def seekable(self) -> bool: ...

    @property
    def closed(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def mode(self) -> str: ...

    def __enter__(self) -> "PyroFile": ...
    def __exit__(self, *args: object) -> bool: ...

    def readline(self, size: int = -1) -> NoReturn: ...
    def readlines(self, hint: int = -1) -> NoReturn: ...
    def writelines(self, lines: object) -> NoReturn: ...
    def fileno(self) -> NoReturn: ...
    def truncate(self, size: int | None = None) -> NoReturn: ...
    def isatty(self) -> bool: ...
    def __iter__(self) -> NoReturn: ...
    def __next__(self) -> NoReturn: ...
